version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - storedb:/var/lib/mysql  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345678

  web:
    image: ahmed0130/todo-app
    container_name: todo-app
    ports:
      - "8000:8000"
    depends_on:
      - db  
    environment:
      - DB_NAME=todo
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_HOST=db

volumes:
  storedb:

